import { MicroCMSListResponse } from "microcms-js-sdk";
import type { NextPage } from "next";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Link from "next/link";
import { client } from "../../libs/client";
import { Blog } from "../types/blog";

// components
import Header from "./parts/Header"
import Footer from "./parts/Footer"

type Props = {
  blog: Blog[];
};

const Home: NextPage<Props> = ({ blog }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>

        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>

        <p className={styles.description}>
          {/* Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code> */}
        </p>

        <div className={styles.grid}>
          {blog.map((blog) => (
            <div key={blog.id}>
              <Link href={`/blog/${blog.id}`}>
                <a>{blog.title}</a>
              </Link>
              <div
                dangerouslySetInnerHTML={{
                  __html: `${blog.content}`,
                }}
              />
            </div>
          ))}
        </div>
      </main>

      <Footer />
    </div>
  )
}


export const getStaticProps = async () => {
  const data = await client.get<MicroCMSListResponse<Blog>>({
    endpoint: "blogs",
  });

  return {
    props: {
      blog: data.contents,
    },
  };
};


export default Home;